### ISSUE TITLE
configure_gps_command 

### ISSUE THREAD

**Issue by svdrummer** [floathub/device#1]
For NEO 6M
configure_gps_command 
Dynamic platform model 0x05 (At sea) 06 is Airborne <1g

U-center 22.07 Build 7 Jul 2022 

$PUBX,40 commands are still current.

I have an older MEGA Floathub, and not having any stability issues, however, as Teensy is new, I cant test for current stability

**Comment by floathub** [comment]
The Mega code is still current (will still use it for non-N2K devices).

Are you trying to configure for a new GPS. Or just trying checking if you can compile and burn current to an older Mega-based device?

**Comment by svdrummer** [comment]
Hello.
I am happy with the the Floathub. The NEO6M and floathub has been working fine for years. As a liveaboard, i love it for the monitoring.  I use the NEO on other projects, i just happened to notice your configuration settings for the Dynamic platform model are incorrect or has changed. Thought I would mention it. Both devices have the same config, which would help the system stability. i Gave the global variable name as a reference. Located in the Min INO file, using that variable in the GPS CONFIG sub. Currently the aircraft setting is not really for sea going vessels.

**Comment by floathub** [comment]
Ah, sorry, following you now. 

And yes, you are absolutely right, should be 0x05. Have you by any chance tried compiling and uploading corrected code to your Mega-based FloatHub device?

**Comment by svdrummer** [comment]
I don't have access to the Floathub for one week. I am away from boat. I would also need to make a lead. I did try the two setting using an esp32 and a NEO6M. Using 0x06 i found the location was all over the place, even with averaging. 
Airborne setting is okay if you have a PID/accelerometer. I have also noticed NEO changed it;s default setting in manufacture from portable to airborne by default(markets for quad copters i guess), 
I do know that my Floathub with MEGA and NEO6M is very stable. I dont mess with the floathub unit under the principle (if it isn't broken, dont fix it) In the MEGA version, I see the config is commented out....this would mean the potential for stability changes depending on the default settings from your supplier. My supplier has a setting of airborne now. (A genuine NEO chip)
For what it's worth, i could only track this down because your code writers have done such an excellent job with the code structure and comments/meaningful variables. PS. Any config string changes would mean the string checksum changes.
In my static testing viewing the deviation map, AirBorne just seemed to jump all over the place.  I "think" is focuses on vertical deviation more than Horizontal.

**Comment by floathub** [comment]
Understood, and thanks again (on all counts). We will get through some testing on this and then push the change and mark as resolved. Really appreciate the super helpful feedback on this.

**Comment by svdrummer** [comment]
I have one of these units and have used it for years. Reliable devices and a great device. This is just a discussion and not a "Fault" or problem. 
I am closing this, as the message has been passed on. This is not an ISSUE as such.

**Comment by floathub** [comment]
Thanks svdrummer. We are going to reopen so we have a Todo reminder to make sure we have the platform mode set to 0x05, we get the checksum right, and we can verify with some test units that we can see better fix behavior. Then we'll commit the changes back in and mark as closed.

**Comment by svdrummer** [comment]
Code updated a year ago. Stale issue.

**Comment by svdrummer** [comment]
Just as a followup.
I see the change made to the mega.ino file to
   uint8_t configure_gps_command[] = {
      0xB5, 0x62,			// Ublox "sync" characters
      0x06, 0x24, 		// Message class and ID (class is configuration, id is navigation confiuration 
      0x24, 0x00, 		// 0x24 = 36 bytes in length of rest of message
      0xFF, 0xFF, 		// Mask (all on = apply all settings that follow)
      0x05,			// Set Dynamic platform model to 5 ("at sea") 
      0x03, 			// Set fix mode to Auto 2D/3D
      0x00, 0x00, 0x00, 0x00,	// Fixed altitude for 2D Mode 
      0x10, 0x27, 0x00, 0x00, 	// Fixed altitude variance for 2D Mode 
      0x05,			// Min elevation for a satellite to be used 
      0x00,			// Max time to perform an extrapolation if GPS signal lost 
      0xFA, 0x00, 		// Position DOP Mask
      0xFA, 0x00, 		// Time DOP Mask
      0x64, 0x00, 		// Position Accuracy Mask
      0x2C, 0x01, 		// Time Accuracy Mask
      0x1A, 			// Static Hold Threshold
      //0x24, 			// Static Hold Threshold 40 Hex = 36 cm/s = 0.75 knot
      //0x4D, 			// Static Hold Threshold 40 Hex = 77 cm/s = 1.5 knot
      0x00,			// DGPS timeout 
      0x00, 0x00, 0x00, 0x00, 	// Always zero
      0x00, 0x00, 0x00, 0x00, 	// Always zero
      0x00, 0x00, 0x00, 0x00, 	// Always zero
      0x2F, 0x26 };

Just as a comment...Doesnt the checksum need to be changed to suit?
0x2F, 0x26 checksum is the same when the change was made from  0x06,	to 0x05		// Set Dynamic platform model to 5 ("at sea")

**Comment by floathub** [comment]
When we changed the Code to switch from Mode 6 to Mode 5, we also changed the checksum from:

        0x30, 0x48

to:

        0x2F, 0x26

Diff is here:

        https://github.com/floathub/device/commit/fdbf1facde9463f4aa786d41f67f0d775f4d2d30

Does that match with what you are seeing?

**Comment by svdrummer** [comment]
My apologies, I miscalculated the checksum :) Was also looking at an old GIT

**Comment by floathub** [comment]
No need to apologize, always good to have another set of eyes to double check on things  :-)
